# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('first_app', '0003_auto_20170210_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='all_users',
        ),
        migrations.AddField(
            model_name='product',
            name='all_users',
            field=models.ManyToManyField(related_name='all_products', to='log_reg.User'),
        ),
    ]
